import Footer from "./components/footer";
import Header from "./components/header";
import "./globals.css";
import { Metadata } from "next";
import { ErrorWrapper } from "./error-wrapper";

export const metadata:Metadata = {
  title: {
    default:"Main title for everypage",
    template:"%s",
    absolute:"use this to change parents info"
  },
  description: "Generated by Next.js",
};

export default function Revenue({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <ErrorWrapper>
        {children}
        </ErrorWrapper>
        <Footer />
      </body>
    </html>
  );
}
